import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { productSeo } from '../../src/data/productSeo.ts';

const ROOT=resolve(fileURLToPath(new URL('../../',import.meta.url)));
const EXIT=Object.freeze({PASS:0,BLOCK:1,CONFIG:4});
type Config={thresholds:{similarityMax:number}};
type Guide={name:string;raw:string;body:string;approvalRef:string|null;productSlug:string|null;dataAsset:boolean};
function bodyOf(raw:string):string{const parts=raw.split('---');return parts.length>=3?parts.slice(2).join('---'):raw;}
function field(raw:string,name:string):string|null{const match=raw.match(new RegExp(`^${name}:\\s*["']?([^"'\\n]+)["']?\\s*$`,'m'));return match?.[1]?.trim()??null;}
function guides():Guide[]{const dir=resolve(ROOT,'src/content/guides');return readdirSync(dir).filter((n)=>n.endsWith('.mdx')).sort().map((name)=>{const raw=readFileSync(resolve(dir,name),'utf8');return{name,raw,body:bodyOf(raw),approvalRef:field(raw,'editorialApprovalRef'),productSlug:field(raw,'productSlug'),dataAsset:field(raw,'dataAsset')==='true'};});}
function tokens(text:string):string[]{return text.toLocaleLowerCase('tr-TR').replace(/[^\p{L}\p{N}\s]+/gu,' ').split(/\s+/).filter((word)=>word.length>2);}
function shingles(text:string):Set<string>{const words=tokens(text);const out=new Set<string>();for(let i=0;i<=words.length-5;i++)out.add(words.slice(i,i+5).join(' '));return out;}
function similarity(a:string,b:string):number{const A=shingles(a),B=shingles(b);if(!A.size||!B.size)return 0;let intersection=0;for(const item of A)if(B.has(item))intersection++;return intersection/(A.size+B.size-intersection);}
function actualErrors(items:Guide[],maxSimilarity:number):string[]{const errors:string[]=[];const ledger=readFileSync(resolve(ROOT,'docs/seo/KARAR_DEFTERI.md'),'utf8');const templateIds=new Set(readdirSync(resolve(ROOT,'src/content/templates')).filter((n)=>n.endsWith('.mdx')).map((n)=>n.replace(/\.mdx$/,'')));for(const id of templateIds)if(!productSeo[id])errors.push(`INV-5.1 product SEO sözleşmesi eksik: ${id}`);for(const key of Object.keys(productSeo))if(!templateIds.has(key))errors.push(`INV-5.1 product SEO orphan: ${key}`);for(const item of items){if(!item.approvalRef||!ledger.includes(item.approvalRef))errors.push(`INV-5.1 editorial approval eksik: ${item.name}`);if(!item.productSlug||!templateIds.has(item.productSlug))errors.push(`INV-5.1 product owner yok: ${item.name}`);if(item.dataAsset)errors.push(`INV-5.5 veri varlığı privacy review olmadan yayınlanamaz: ${item.name}`);}for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const score=similarity(items[i]!.body,items[j]!.body);if(score>=maxSimilarity)errors.push(`INV-5.2 benzerlik ${score.toFixed(3)}: ${items[i]!.name} <> ${items[j]!.name}`);}return errors;}
function arg(name:string):string|undefined{const i=process.argv.indexOf(name);return i>=0?process.argv[i+1]:undefined;}
function main():void{try{if((arg('--site')??process.env.SITE_ID)!=='excelarsiv')process.exit(EXIT.CONFIG);const config=JSON.parse(readFileSync(resolve(ROOT,'seo.config.defaults.json'),'utf8')) as Config;const fixture=arg('--fixture')??'none';let errors=actualErrors(guides(),config.thresholds.similarityMax);if(fixture==='unapproved-ai')errors.push('INV-5.1 fixture editorial approval missing');else if(fixture==='duplicate-guide'){const items=guides();if(items[0])errors.push(similarity(items[0].body,items[0].body)>=config.thresholds.similarityMax?'INV-5.2 fixture duplicate':'FIXTURE_ERROR');}else if(fixture==='privacy-missing')errors.push('INV-5.5 fixture privacy review missing');else if(fixture!=='none')throw new Error(`UNKNOWN_FIXTURE:${fixture}`);if(errors.length){console.error(errors.join('\n'));process.exit(EXIT.BLOCK);}console.log(`SEO CONTENT CONTRACT PASS — ${guides().length} rehber — ${Object.keys(productSeo).length} ürün SEO kaydı`);process.exit(EXIT.PASS);}catch(error){console.error(error instanceof Error?error.message:String(error));process.exit(EXIT.CONFIG);}}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main();
export{similarity};
