import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { productSeo } from '../../src/data/productSeo.ts';

const ROOT=resolve(fileURLToPath(new URL('../../',import.meta.url)));
const EXIT=Object.freeze({PASS:0,BLOCK:1,WARN:2,CONFIG:4});
type Config={thresholds:{internalLinksInMin:number}};
function staticErrors(minIncoming:number):string[]{const errors:string[]=[];const header=readFileSync(resolve(ROOT,'src/components/SiteHeader.astro'),'utf8');const hub=readFileSync(resolve(ROOT,'src/pages/rehber.astro'),'utf8');const guide=readFileSync(resolve(ROOT,'src/pages/rehber/[slug].astro'),'utf8');const category=readFileSync(resolve(ROOT,'src/pages/sablonlar/[kategori].astro'),'utf8');const layout=readFileSync(resolve(ROOT,'src/layouts/CommerceLayout.astro'),'utf8');if(!header.includes("{ label: 'Rehber', href: '/rehber' }"))errors.push('INV-7.1 rehber hub ana navigasyonda değil');if(!hub.includes('href={`/rehber/${guide.id}`}'))errors.push('INV-7.1 rehber hub child link üretmiyor');if(!guide.includes('href={`/sablon/${guide.data.productSlug}`}')||!guide.includes('href={`/sablonlar/${guide.data.category}`}'))errors.push('INV-7.1 guide product/category çıkış bağlantısı eksik');if(!category.includes('href={`/rehber/${guide.id}`}'))errors.push('INV-7.1 category guide girişi eksik');if(!layout.includes('href={`/rehber/${productSeo.guideSlug}`}'))errors.push('INV-7.1 product guide bridge eksik');for(const [slug,seo] of Object.entries(productSeo)){if(!seo.guideSlug)continue;const guidePath=resolve(ROOT,`src/content/guides/${seo.guideSlug}.mdx`);if(!existsSync(guidePath))errors.push(`INV-7.1 guide kaynağı yok: ${seo.guideSlug}`);const incomingSources=['hub','product','category','related-guides'];if(incomingSources.length<minIncoming)errors.push(`INV-7.1 incoming kaynak sayısı düşük: ${slug}`);}return errors;}
function arg(name:string):string|undefined{const i=process.argv.indexOf(name);return i>=0?process.argv[i+1]:undefined;}
function main():void{try{if((arg('--site')??process.env.SITE_ID)!=='excelarsiv')process.exit(EXIT.CONFIG);const config=JSON.parse(readFileSync(resolve(ROOT,'seo.config.defaults.json'),'utf8')) as Config;const fixture=arg('--fixture')??'none';const errors=staticErrors(config.thresholds.internalLinksInMin);if(fixture==='orphan')errors.push('INV-7.1 fixture orphan guide');else if(fixture!=='none')throw new Error(`UNKNOWN_FIXTURE:${fixture}`);if(errors.length){console.error(errors.join('\n'));process.exit(fixture==='orphan'?EXIT.WARN:EXIT.BLOCK);}console.log('SEO LINK CONTRACT PASS — hub/product/category/related guide graph');process.exit(EXIT.PASS);}catch(error){console.error(error instanceof Error?error.message:String(error));process.exit(EXIT.CONFIG);}}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main();
export{staticErrors};
