import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(fileURLToPath(new URL('../../', import.meta.url)));
const DATE_FLOOR = '2025-09-11';
const EXIT = Object.freeze({ PASS: 0, BLOCK: 1, WARN: 2, MISSING_DATA: 3, CONFIG: 4 });
function readJson(path:string){ return JSON.parse(readFileSync(resolve(ROOT,path),'utf8')); }
function mergeDeep(base:any,override:any):any{ if(Array.isArray(base)||Array.isArray(override)) return override??base; if(base&&override&&typeof base==='object'&&typeof override==='object'){const out={...base}; for(const [k,v] of Object.entries(override)) out[k]=k in out?mergeDeep(out[k],v):v; return out;} return override??base; }
function parseArgs(argv:string[]){const i=argv.indexOf('--site'); return {site:i>=0?argv[i+1]:process.env.SITE_ID};}
function progress(){const text=readFileSync(resolve(ROOT,'docs/seo/PROGRESS.md'),'utf8'); const m=text.match(/<!--\s*SEO_PROGRESS\s+(\{[^\n]+\})\s*-->/); if(!m) throw new Error('PROGRESS_META_MISSING'); return JSON.parse(m[1]);}
function typeOk(value:any,type:any):boolean{if(Array.isArray(type))return type.some(t=>typeOk(value,t)); if(type==='null')return value===null;if(type==='array')return Array.isArray(value);if(type==='integer')return Number.isInteger(value);if(type==='number')return typeof value==='number'&&Number.isFinite(value);if(type==='object')return value!==null&&typeof value==='object'&&!Array.isArray(value);return typeof value===type;}
function validateSchema(value:any,schema:any,path='$'):string[]{const errors:string[]=[];if(schema.type!==undefined&&!typeOk(value,schema.type))return [`${path}: type`];if(schema.const!==undefined&&value!==schema.const)errors.push(`${path}: const`);if(schema.enum&&!schema.enum.some((x:any)=>Object.is(x,value)))errors.push(`${path}: enum`);if(typeof value==='string'){if(schema.pattern&&!new RegExp(schema.pattern).test(value))errors.push(`${path}: pattern`);if(schema.minLength!==undefined&&value.length<schema.minLength)errors.push(`${path}: minLength`);if(schema.maxLength!==undefined&&value.length>schema.maxLength)errors.push(`${path}: maxLength`);if(schema.format==='date'&&!/^\d{4}-\d{2}-\d{2}$/.test(value))errors.push(`${path}: date format`);}if(typeof value==='number'){if(schema.minimum!==undefined&&value<schema.minimum)errors.push(`${path}: minimum`);if(schema.maximum!==undefined&&value>schema.maximum)errors.push(`${path}: maximum`);}if(Array.isArray(value)){if(schema.minItems!==undefined&&value.length<schema.minItems)errors.push(`${path}: minItems`);if(schema.uniqueItems&&new Set(value.map((x:any)=>JSON.stringify(x))).size!==value.length)errors.push(`${path}: uniqueItems`);if(schema.items)value.forEach((v:any,i:number)=>errors.push(...validateSchema(v,schema.items,`${path}[${i}]`)));}if(value&&typeof value==='object'&&!Array.isArray(value)){for(const key of schema.required??[])if(!(key in value))errors.push(`${path}.${key}: required`);for(const [key,sub] of Object.entries(schema.properties??{}))if(key in value)errors.push(...validateSchema(value[key],sub,`${path}.${key}`));if(schema.additionalProperties===false){const allowed=new Set(Object.keys(schema.properties??{}));for(const key of Object.keys(value))if(!allowed.has(key))errors.push(`${path}.${key}: additionalProperties`);}else if(schema.additionalProperties&&typeof schema.additionalProperties==='object'){const known=new Set(Object.keys(schema.properties??{}));for(const [key,v] of Object.entries(value))if(!known.has(key))errors.push(...validateSchema(v,schema.additionalProperties,`${path}.${key}`));}}if(schema.not&&validateSchema(value,schema.not,path).length===0)errors.push(`${path}: not`);return errors;}
function scanPlaceholders(value:any,path='$',out:string[]=[]):string[]{if(typeof value==='string'&&value.includes('|'))out.push(path);else if(Array.isArray(value))value.forEach((x,i)=>scanPlaceholders(x,`${path}[${i}]`,out));else if(value&&typeof value==='object')for(const [k,v] of Object.entries(value))scanPlaceholders(v,`${path}.${k}`,out);return out;}
function globToRegExp(glob:string){const escaped=glob.replace(/[.+^${}()|[\]\\]/g,'\\$&').replace(/\*\*/g,'§§').replace(/\*/g,'[^/]*').replace(/§§/g,'.*');return new RegExp(`^${escaped}$`);}
function matchAny(path:string,patterns:string[]){return patterns.some(g=>globToRegExp(g).test(path));}
function changedFiles(){if(process.env.SEO_CHANGED_FILES)return process.env.SEO_CHANGED_FILES.split(',').map(x=>x.trim()).filter(Boolean);try{const base=process.env.GITHUB_BASE_REF;const args=base?['diff','--name-only',`origin/${base}...HEAD`]:['diff','--name-only','HEAD'];return execFileSync('git',args,{cwd:ROOT,encoding:'utf8'}).trim().split('\n').filter(Boolean);}catch{return [];}}
function phaseContract(p:any){const contracts=readJson('PHASE_CONTRACTS.json');if((p.bootstrap==='active'||p.bootstrap==='completed')&&p.activePhase===null)return contracts.bootstrap;if(Number.isInteger(p.activePhase))return contracts[`faz-${String(p.activePhase).padStart(2,'0')}`];return null;}
function secretHits(files:string[]){const patterns=[/github_pat_[A-Za-z0-9_]{20,}/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/\bAKIA[0-9A-Z]{16}\b/,/\bAIza[0-9A-Za-z_-]{20,}\b/,/\bsk-[A-Za-z0-9]{20,}\b/];const hits:string[]=[];for(const file of files){const abs=resolve(ROOT,file);if(!existsSync(abs)||/\.(xlsx|png|jpe?g|gif|webp|pdf)$/i.test(file))continue;const text=readFileSync(abs,'utf8');for(const re of patterns)if(re.test(text))hits.push(`${file}:${re.source}`);}return hits;}
function mandateInvariantIds(){const text=readFileSync(resolve(ROOT,'docs/seo/MANDATE.md'),'utf8');return [...new Set([...text.matchAll(/\*\*(INV-[A-Z0-9.]+(?:[ab])?) \[(?:BLOCK|WARN|INFO)\]\*\*/g)].map(m=>m[1]))].sort();}
function artifactEnvelopeErrors(){const candidates=['data/seo/tam_map.json','data/seo/slo_history.json','data/seo/calibration_report.json','data/seo/pnl.json','data/seo/portfolio_board.json','data/seo/valuation.json','data/seo/brand_demand.json','data/seo/linkable_assets.json','data/seo/cro_experiments.json'];const required=['artifact','schemaVersion','generatedAt','generatorScript','inputWindow','confidence','partial','siteId','coldStart','structuralBreaksApplied'];const errors:string[]=[];for(const file of candidates)if(existsSync(resolve(ROOT,file))){const x=readJson(file);for(const k of required)if(!(k in (x.meta??{})))errors.push(`${file}:meta.${k}`);}return errors;}
function containsGuarantee(text:string){const hard=/(kesin\s+çıkar|#1\s+ol|\bguaranteed\b|şunu\s+yaparsan[^\n]{0,40}çıkarsın)/iu;if(hard.test(text))return true;for(const line of text.split(/\r?\n/)){if(!/\bgaranti\b/iu.test(line))continue;const compliance=/(garanti[^\n]{0,45}(?:yok|yasak|vermez|değildir|taramas|örüntüsü)|(?:yok|yasak)[^\n]{0,45}garanti)/iu;if(!compliance.test(line))return true;}return false;}
function reviewTextGuaranteeHit(){const direct=process.env.SEO_REVIEW_TEXT??'';let commits='';try{if(process.env.GITHUB_BASE_REF)commits=execFileSync('git',['log',`origin/${process.env.GITHUB_BASE_REF}..HEAD`,'--format=%B'],{cwd:ROOT,encoding:'utf8'});else commits=execFileSync('git',['log','-1','--format=%B'],{cwd:ROOT,encoding:'utf8'});}catch{}return containsGuarantee(`${direct}\n${commits}`);}
function guaranteeHits(files:string[]){const excluded=new Set(['docs/seo/MANDATE.md','docs/seo/MANDATE_ERRATA.md','docs/seo/YORUM_KAYDI.md','data/seo/invariants.json']);const hits:string[]=[];for(const file of files){if(excluded.has(file)||file.startsWith('scripts/seo/')||file.startsWith('tests/conformance/')||file.includes('/fixtures/')||file.includes('/invariants/'))continue;const abs=resolve(ROOT,file);if(!existsSync(abs)||!/\.(md|txt|json|ya?ml|mjs|cjs|js|ts|astro)$/i.test(file))continue;if(containsGuarantee(readFileSync(abs,'utf8')))hits.push(file);}return hits;}
function runPreflight({site,files=changedFiles()}:{site?:string,files?:string[]}){const checks:any[]=[];const fail=(id:string,msg:string,code=EXIT.BLOCK)=>checks.push({id,status:'FAIL',msg,code});const pass=(id:string,msg:string)=>checks.push({id,status:'PASS',msg,code:0});if(!site){fail('P-09','--site/SITE_ID eksik',EXIT.CONFIG);return checks;}const defaults=readJson('seo.config.defaults.json');const local=readJson(`sites/${site}/seo.config.json`);const config=mergeDeep(defaults,local);const schema=readJson('seo.config.schema.json');const schemaErrors=validateSchema(config,schema);schemaErrors.length?fail('P-01',schemaErrors.join('; '),EXIT.CONFIG):pass('P-01','config schema PASS');const placeholders=scanPlaceholders(config);placeholders.length?fail('P-02',`placeholder: ${placeholders.join(',')}`,EXIT.CONFIG):pass('P-02','placeholder yok');const p=progress();const contract=phaseContract(p);if(!contract)fail('P-03','aktif phase contract yok',EXIT.CONFIG);else{const bad=files.filter(f=>!matchAny(f,contract.writes)||matchAny(f,contract.forbidsWrites??[]));bad.length?fail('P-03',`manifest dışı: ${bad.join(',')}`):pass('P-03',`manifest uyumlu (${files.length} değişiklik)`);}const secrets=secretHits(files);secrets.length?fail('P-04',`secret bulundu: ${secrets.join(',')}`):pass('P-04','secret izi yok');const inv=readJson('data/seo/invariants.json').map((x:any)=>x.id).sort();const mids=mandateInvariantIds();JSON.stringify(inv)===JSON.stringify(mids)?pass('P-05',`invariant parity ${inv.length}`):fail('P-05',`invariant parity bozuk json=${inv.length} mandate=${mids.length}`,EXIT.CONFIG);const envelope=artifactEnvelopeErrors();envelope.length?fail('P-06',envelope.join(',')):pass('P-06','mevcut artefakt zarfları PASS');const b=config.economics.budgetSplit;const sum=b.investPct+b.holdPct+b.harvestPct+b.divestPct;sum===100?pass('P-07','budgetSplit=100'):fail('P-07',`budgetSplit=${sum}`,EXIT.CONFIG);const date=config.measurement.dataWindowStart;/^\d{4}-\d{2}-\d{2}$/.test(date)&&date>=DATE_FLOOR?pass('P-08',`dataWindowStart=${date}`):fail('P-08',`dataWindowStart=${date} < ${DATE_FLOOR}`,EXIT.CONFIG);config.site.siteId===site?pass('P-09',`siteId=${site}`):fail('P-09',`siteId mismatch ${config.site.siteId}`,EXIT.CONFIG);const gh=guaranteeHits(files);const reviewHit=reviewTextGuaranteeHit();(gh.length||reviewHit)?fail('P-10',`garanti/vaat dili: ${[...gh,...(reviewHit?['PR/commit metni']:[])].join(',')}`):pass('P-10','garanti/vaat örüntüsü yok');return checks;}
function exitCode(checks:any[]){return checks.reduce((max,c)=>Math.max(max,c.code),0);}
function main(){const {site}=parseArgs(process.argv.slice(2));try{const checks=runPreflight({site});for(const c of checks)console.log(`${c.id} ${c.status} — ${c.msg}`);const code=exitCode(checks);console.log(`SEO PREFLIGHT — ${checks.filter(x=>x.status==='PASS').length}/${checks.length} PASS — exit ${code}`);process.exit(code);}catch(err){console.error(`PREFLIGHT CONFIG ERROR — ${err instanceof Error?err.message:String(err)}`);process.exit(EXIT.CONFIG);}}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url))main();
export {EXIT,DATE_FLOOR,mergeDeep,validateSchema,scanPlaceholders,globToRegExp,matchAny,containsGuarantee,reviewTextGuaranteeHit,guaranteeHits,runPreflight,exitCode,progress};
