// 12 ürünün tek kaynak verisi: MDX üretimi + demo xlsx üretimi buradan beslenir.
export const products = [
  {
    name: 'Akıllı Kasa Defteri ve Nakit Kontrol Sistemi',
    category: 'nakit-akisi',
    priceTL: 990,
    summary: 'Kasa hareketlerini günlük işleyin, bakiye ile fiili sayım farkını anında görün. Dönem sonu kontrolü için hazır yapı.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Kasa hareketlerinin işlendiği sayfa',
        kind: 'input',
        headers: ['Tarih', 'Açıklama', 'Gelir (₺)', 'Gider (₺)', 'Kaynak'],
        rows: [
          ['01.08.2026', 'Günlük satış tahsilatı', 18500, 0, 'POS'],
          ['02.08.2026', 'Kırtasiye alımı', 0, 640, 'Fiş'],
          ['03.08.2026', 'Müşteri ödemesi', 4300, 0, 'Havale'],
          ['04.08.2026', 'Fatura ödemesi', 0, 7200, 'Banka'],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Günlük bakiye ve sayım farkı formülleri',
        kind: 'calculation',
        headers: ['Tarih', 'Gelir (₺)', 'Gider (₺)', 'Kapanış Bakiyesi (₺)', 'Fiili Sayım (₺)', 'Fark (₺)'],
        rows: [
          ['01.08.2026', '=Girdi!C2', '=Girdi!D2', '=E2+B3-C3', '', ''],
          ['02.08.2026', '=Girdi!C3', '=Girdi!D3', '=E3+B4-C4', '', ''],
          ['03.08.2026', '=Girdi!C4', '=Girdi!D4', '=E4+B5-C5', '', ''],
          ['04.08.2026', '=Girdi!C5', '=Girdi!D5', '=E5+B6-C6', 15960, '=F6-E6'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Aylık özet ve dönem sonu kontrolü',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam Gelir (₺)', '=TOPLA(Hesap!B2:B5)'],
          ['Toplam Gider (₺)', '=TOPLA(Hesap!C2:C5)'],
          ['Net Nakit Değişimi (₺)', '=B2-B3'],
          ['Kapanış Bakiyesi (₺)', '=Hesap!E6'],
          ['Sayım Farkı (₺)', '=Hesap!F6'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Tarih ve kasa hareketi açıklaması', 'Gelir ve gider tutarları', 'Kaynak bilgisi (POS, havale, fiş)'],
    outputs: ['Günlük kapanış bakiyesi', 'Dönem toplam gelir ve gider', 'Sayım farkı uyarısı'],
    suitableFor: ['Perakende ve hizmet işletmeleri', 'Günlük nakit işleyen KOBİ\'ler', 'Kasa sayımı yapılan dönem sonu kontrolleri'],
    notSuitableFor: ['Cari hesap ve fatura takibi', 'Banka mutabakatı'],
    requirements: ['Excel 2016 veya üzeri', 'Formüller için değişken hücre yok'],
    updatePolicy: 'Yapı değişmediği sürece güncel sürüm aynıdır; mevzuat veya Excel davranışı değişirse güncel sürüm satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Kasa defterini günlük işlemek zorunlu mu?', answer: 'Hayır. Girdi sayfasına hareketleri haftalık da işleyebilirsiniz; bakiyeler yine doğru hesaplanır. Günlük işleme, sayım farkını erken yakalamanızı sağlar.' },
      { question: 'Sayım farkı nasıl hesaplanıyor?', answer: 'Fiili sayımı Hesap sayfasına girdiğinizde fark, kapanış bakiyesi ile fiili sayım arasındaki fark olarak otomatik hesaplanır.' },
      { question: 'Dövizli işlem girebilir miyim?', answer: 'Bu yapı TL bazlıdır. Dövizli kasalar için banka ve döviz modeli ayrı sistemdedir.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; formüller modern işlevler kullanmaz, eski sürümlerde de çalışır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir. Formül sayfaları koruma ile kilitlidir; koruma şifresizdir, kaldırıp formülleri inceleyebilirsiniz.' },
      { question: 'Birden fazla kasa şubem var, uyar mı?', answer: 'Şube başına ayrı dosya açabilir veya Girdi sayfasına Şube kolonu ekleyerek tek dosyada toplayabilirsiniz.' },
    ],
    related: ['günlük-gelir-gider-ve-gerçek-kârlılık-sistemi', 'banka-kredi-ve-taksit-takip-sistemi'],
  },
  {
    name: '13 Haftalık Nakit Akışı ve Ödeme Planlama Sistemi',
    category: 'nakit-akisi',
    priceTL: 2490,
    summary: '13 haftalık nakit modeliyle giriş-çıkış tahminlerini planlayın; kritik haftaları önceden görüp ödeme önceliği verin.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Haftalık tahmin girişleri',
        kind: 'input',
        headers: ['Hafta', 'Gelen Nakit (₺)', 'Giden Nakit (₺)', 'Not'],
        rows: [
          ['Hafta 1', 42000, 38500, 'KDV ödemesi'],
          ['Hafta 2', 38000, 41000, 'Maaş dönemi'],
          ['Hafta 3', 45000, 36000, ''],
          ['Hafta 4', 30000, 44000, 'SGK + vergi'],
        ],
      },
      {
        name: 'Hesap',
        purpose: '13 haftalık kümülatif model',
        kind: 'calculation',
        headers: ['Hafta', 'Başlangıç (₺)', 'Gelen (₺)', 'Giden (₺)', 'Bitiş (₺)', 'Kümülatif (₺)'],
        rows: [
          ['Hafta 1', 15000, '=Girdi!C2', '=Girdi!D2', '=B2+C2-D2', '=E2'],
          ['Hafta 2', '=E2', '=Girdi!C3', '=Girdi!D3', '=B3+C3-D3', '=E3'],
          ['Hafta 3', '=E3', '=Girdi!C4', '=Girdi!D4', '=B4+C4-D4', '=E4'],
          ['Hafta 4', '=E4', '=Girdi!C5', '=Girdi!D5', '=B5+C5-D5', '=E5'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Kritik hafta uyarıları ve ödeme planı',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['En düşük kümülatif bakiye (₺)', '=MIN(Hesap!F2:F5)'],
          ['En düşük hafta', '=INDEX(Hesap!A2:A5;MATCH(Hesap!F2:F5;MIN(Hesap!F2:F5);0))'],
          ['Toplam gelen (₺)', '=TOPLA(Hesap!C2:C5)'],
          ['Toplam giden (₺)', '=TOPLA(Hesap!D2:D5)'],
          ['Net (₺)', '=B4-B5'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Haftalık nakit girişi tahmini', 'Haftalık nakit çıkışı tahmini', 'Ödeme takvimi notları'],
    outputs: ['13 haftalık kümülatif bakiye eğrisi', 'Kritik (eksi) hafta uyarısı', 'Dönem net nakit değişimi'],
    suitableFor: ['Mevsimselliği olan işletmeler', 'Ödeme tarihleri kesişen KOBİ\'ler', 'Yatırım veya alım öncesi nakit planlaması'],
    notSuitableFor: ['Kasa defteri işleme', 'Yıllık bütçe detayı'],
    requirements: ['Excel 2016 veya üzeri', 'DİZİ formülleri çalıştıran sürüm'],
    updatePolicy: 'Mevzuat değişikliği bu yapıyı etkilemediği için sürüm güncellemeleri iyileştirme kapsamında sunulur; kullanıcıya 12 ay ücretsizdir.',
    faq: [
      { question: '13 hafta neden seçildi?', answer: '13 haftalık dönem, bir çeyreği karşılar ve nakit krizlerinin çoğu bu pencerede öngörülebilir. Daha uzun dönemler tahmin güvenilirliğini düşürür.' },
      { question: 'Tahminleri ne sıklıkla güncellemeliyim?', answer: 'Haftalık güncelleme önerilir. Gerçekleşen hafta verisini girerken sonraki haftaların tahminini de düzeltmeniz modeli canlı tutar.' },
      { question: 'Kritik hafta uyarısı nasıl çalışır?', answer: 'Hesap sayfasındaki kümülatif bakiye eksiye düşen hafta, Çıktı sayfasında en düşük hafta olarak gösterilir; böylece ödeme önceliklendirmesini o haftaya göre yaparsınız.' },
      { question: 'Dövizli giriş-çıkış girebilir miyim?', answer: 'Yapı TL bazlıdır; döviz hareketlerini TL karşılığıyla girmeniz önerilir.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir. INDEX/MATCH yapısı modern sürümlerde sorunsuz çalışır.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['akıllı-kasa-defteri-ve-nakit-kontrol-sistemi', 'kobi-finans-yönetim-paketi'],
  },
  {
    name: 'Cari Hesap, Tahsilat ve Müşteri Risk Takip Sistemi',
    category: 'muhasebe-ve-vergi',
    priceTL: 1490,
    summary: 'Fatura, tahsilat ve vade takibini tek yapıda toplayın; vadesi geçen bakiyeleri müşteri risk skoruyla önceliklendirin.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Fatura ve tahsilat girişleri',
        kind: 'input',
        headers: ['Tarih', 'Müşteri', 'Fatura Tutarı (₺)', 'Tahsilat (₺)', 'Vade', 'Durum'],
        rows: [
          ['05.07.2026', 'Alfa Yapı Ltd.', 24800, 0, '05.08.2026', 'Bekliyor'],
          ['12.07.2026', 'Beta Tekstil A.Ş.', 12600, 12600, '12.08.2026', 'Ödendi'],
          ['18.07.2026', 'Gama Gıda San.', 9800, 0, '18.07.2026', 'Vadesi geçti'],
          ['22.07.2026', 'Delta İnşaat', 15400, 5000, '22.08.2026', 'Kısmi'],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Müşteri bazlı bakiye ve risk skoru',
        kind: 'calculation',
        headers: ['Müşteri', 'Toplam Borç (₺)', 'Tahsilat (₺)', 'Bakiye (₺)', 'Vadesi Geçen (₺)', 'Gecikme (gün)', 'Risk'],
        rows: [
          ['Alfa Yapı Ltd.', '=TOPLA(Girdi!C2:Girdi!C5)', '=TOPLA(Girdi!D2:Girdi!D5)', '=B2-C2', '=EĞER(Girdi!F2<BUGÜN();Girdi!C2-Girdi!D2;0)', 0, '=EĞER(D2>0;"İzle";"")'],
          ['Beta Tekstil A.Ş.', '=Girdi!C3', '=Girdi!D3', '=B3-C3', 0, 0, ''],
          ['Gama Gıda San.', '=Girdi!C4', '=Girdi!D4', '=B4-C4', '=EĞER(Girdi!F4<BUGÜN();Girdi!C4-Girdi!D4;0)', '=BUGÜN()-Girdi!F4', 'Kritik'],
          ['Delta İnşaat', '=Girdi!C5', '=Girdi!D5', '=B5-C5', 0, 0, ''],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Tahsilat öncelik raporu',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam alacak (₺)', '=TOPLA(Hesap!D2:D5)'],
          ['Vadesi geçen toplam (₺)', '=TOPLA(Hesap!E2:E5)'],
          ['Kritik müşteri sayısı', '=EĞERSAY(Hesap!G2:G5;"Kritik")'],
          ['Tahsilat oranı', '=TOPLA(Hesap!C2:C5)/TOPLA(Hesap!B2:B5)'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Fatura tarihi ve tutarı', 'Müşteri adı ve vade tarihi', 'Tahsilat ve durum bilgisi'],
    outputs: ['Müşteri bazlı bakiye ve risk skoru', 'Vadesi geçen tutar ve gecikme günü', 'Tahsilat öncelik listesi'],
    suitableFor: ['Vadeli satış yapan toptancılar', 'Hizmet ve inşaat işletmeleri', 'Müşteri alacak riskini yönetmek isteyenler'],
    notSuitableFor: ['Kasa ve nakit defteri işleme', 'Çek–senet portföyü'],
    requirements: ['Excel 2016 veya üzeri', 'Tarih hesaplarının doğru çalışması için sistem saati'],
    updatePolicy: 'Yapı mevzuattan bağımsızdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Vade takibi otomatik mi?', answer: 'Evet. Girdi sayfasındaki vade tarihi ile bugün arasındaki fark, Hesap sayfasında gecikme günü olarak otomatik hesaplanır.' },
      { question: 'Risk skoru nasıl belirleniyor?', answer: 'Vadesi geçen bakiyesi olan müşteriler "Kritik", düzenli ödeyenler "İzle" olarak işaretlenir. Kendi ölçütünüzü eklerseniz formülü açıp düzenleyebilirsiniz.' },
      { question: 'Kısmi tahsilat girebilir miyim?', answer: 'Evet, tahsilat kolonuna kısmi tutar girilir; bakiye otomatik güncellenir ve durum sizin girişinize bağlı kalır.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; BUGÜN() ve EĞERSAY standart işlevlerdir.' },
      { question: 'Muhasebe programımla entegre çalışır mı?', answer: 'Hayır, bu dosya bağımsız bir takip aracıdır. Verileri muhasebe programınızdan aktarıp izleme yapabilirsiniz.' },
      { question: 'Kaç müşteriye kadar ölçeklenir?', answer: 'Yapı binlerce satıra kadar sorunsuz çalışır; tavsiye edilen dönem içi veri, sayfayı hızlı tutacak şekilde düzenli arşivlemektir.' },
    ],
    related: ['çek-senet-ve-vade-risk-sistemi', 'kobi-finans-yönetim-paketi'],
  },
  {
    name: 'Banka, Kredi ve Taksit Takip Sistemi',
    category: 'nakit-akisi',
    priceTL: 1490,
    summary: 'Tüm banka hesaplarını, kredi taksitlerini ve ödeme tarihlerini tek sayfada izleyin; yaklaşan taksitleri önceden görün.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Banka hareketi ve kredi tanımları',
        kind: 'input',
        headers: ['Tarih', 'Hesap', 'Açıklama', 'Giren (₺)', 'Çıkan (₺)'],
        rows: [
          ['03.08.2026', 'Vadesiz - A', 'Tahsilat', 18500, 0],
          ['04.08.2026', 'Vadesiz - B', 'SGK ödemesi', 0, 8200],
          ['05.08.2026', 'Kredi - A', 'Taksit ödemesi', 0, 6400],
          ['06.08.2026', 'Vadesiz - A', 'Maaş ödemesi', 0, 21500],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Kredi modeli ve taksit takvimi',
        kind: 'calculation',
        headers: ['Taksit No', 'Anapara (₺)', 'Faiz (₺)', 'Taksit Tutarı (₺)', 'Kalan Anapara (₺)', 'Vade'],
        rows: [
          ['1', 9400, 600, '=B2+C2', '=E2-B2', '05.09.2026'],
          ['2', '=E2', 600, '=B3+C3', '=E3-B3', '05.10.2026'],
          ['3', '=E3', 600, '=B4+C4', '=E4-B4', '05.11.2026'],
          ['4', '=E4', 600, '=B5+C5', '=E5-B5', '05.12.2026'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Hesap bakiyeleri ve yaklaşan taksitler',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam banka girişi (₺)', '=TOPLA(Girdi!D2:D5)'],
          ['Toplam banka çıkışı (₺)', '=TOPLA(Girdi!E2:E5)'],
          ['Aylık kredi taksit toplamı (₺)', '=Hesap!D2'],
          ['Kalan kredi anaparası (₺)', '=Hesap!E5'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Banka hesabı ve hareket tutarları', 'Kredi anapara, faiz ve vade bilgisi', 'İşlem açıklaması'],
    outputs: ['Hesap bazlı bakiye takibi', 'Kalan kredi anaparası', 'Yaklaşan taksit tutarı ve tarihi'],
    suitableFor: ['Birden fazla banka hesabı olanlar', 'Kredi ve taksit ödeyen KOBİ\'ler', 'Vadesiz hesapları konsolide izlemek isteyenler'],
    notSuitableFor: ['Kasa defteri', 'Çek–senet takibi'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Birden fazla kredi girilebilir mi?', answer: 'Evet, kredi tanımı için satırlar açıp her krediyi ayrı blok olarak girebilirsiniz; özet sayfasına ek formül eklerseniz otomatik toplanır.' },
      { question: 'Taksit tarihi uyarısı var mı?', answer: 'Yaklaşan taksitler Hesap sayfasındaki vade kolonunda görünür; kendi koşullu biçimlendirmenizi ekleyerek renklendirebilirsiniz.' },
      { question: 'Döviz hesaplarını destekliyor mu?', answer: 'Yapı TL bazlıdır. Döviz hesabı için TL karşılığını girmeniz veya ayrı kolon eklemeniz önerilir.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['akıllı-kasa-defteri-ve-nakit-kontrol-sistemi', 'kobi-finans-yönetim-paketi'],
  },
  {
    name: 'Çek–Senet ve Vade Risk Sistemi',
    category: 'nakit-akisi',
    priceTL: 1490,
    summary: 'Çek ve senet portföyünü vade aralıklarıyla izleyin; tahsilat beklentisini ve riskli kalemleri tek bakışta görün.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Çek–senet portföy girişleri',
        kind: 'input',
        headers: ['Tür', 'Numara', 'Keşideci', 'Vade', 'Tutar (₺)', 'Durum'],
        rows: [
          ['Çek', 'TR-1002', 'Alfa Yapı Ltd.', '30.09.2026', 14800, 'Portföyde'],
          ['Senet', 'SN-088', 'Beta Tekstil A.Ş.', '15.10.2026', 9400, 'Portföyde'],
          ['Çek', 'TR-1005', 'Gama Gıda San.', '20.08.2026', 6200, 'Ciro'],
          ['Senet', 'SN-091', 'Delta İnşaat', '25.11.2026', 12100, 'Portföyde'],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Vade aralığı ve risk analizi',
        kind: 'calculation',
        headers: ['Vade Aralığı', 'Tutar (₺)', 'Riskli Tutar (₺)', 'Kalem Sayısı'],
        rows: [
          ['0-30 gün', '=TOPLA(Girdi!E2:Girdi!E5)', 0, 0],
          ['31-60 gün', 0, 0, 0],
          ['61-90 gün', '=Girdi!E2', 0, 1],
          ['90 gün üzeri', '=Girdi!E3+Girdi!E5', '=Girdi!E3+Girdi!E5', 2],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Tahsilat beklentisi ve risk özeti',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Portföy toplamı (₺)', '=TOPLA(Girdi!E2:E5)'],
          ['Portföydeki tutar (₺)', '=TOPLA(Girdi!E2:Girdi!E5)'],
          ['Vadesi 90 günden uzun (₺)', '=Hesap!B5'],
          ['Riskli kalem sayısı', '=Hesap!D5'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Çek veya senet türü ve numarası', 'Keşideci ve vade tarihi', 'Tutar ve durum bilgisi'],
    outputs: ['Vade aralığına göre tutar dağılımı', 'Riskli kalemlerin toplamı', 'Portföy toplam tutarı'],
    suitableFor: ['Vadeli tahsilat yapan üreticiler', 'Çek–senet kabul eden toptancılar', 'Vade riskini ölçmek isteyen finans yöneticileri'],
    notSuitableFor: ['Cari hesap takibi', 'Banka kredi takibi'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Ciro edilen kalemler nasıl izlenir?', answer: 'Durum kolonuna "Ciro" yazmanız yeterlidir; dilerseniz kendi koşullu biçimlendirmenizle renklendirebilirsiniz.' },
      { question: 'Karşılıksız çek uyarısı var mı?', answer: 'Durum kolonuna "Karşılıksız" yazıp kendi formülünüzle risk toplamına ekleyebilirsiniz; yapı önceden hazır tanım içermez.' },
      { question: 'Vade aralıkları otomatik mi?', answer: 'Demo modelde örnek aralıklar vardır; kendi aralıklarınızı Hesap sayfasındaki formülleri düzenleyerek ayarlayabilirsiniz.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['cari-hesap-tahsilat-ve-müşteri-risk-takip-sistemi', 'kobi-finans-yönetim-paketi'],
  },
  {
    name: 'Günlük Gelir–Gider ve Gerçek Kârlılık Sistemi',
    category: 'satis-ve-fiyatlama',
    priceTL: 1490,
    summary: 'Günlük gelir ve giderleri kategorilerle işleyin; aylık net kârı ve kategori marjını gerçek veriyle görün.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Günlük işlem girişleri',
        kind: 'input',
        headers: ['Tarih', 'Kategori', 'Gelir (₺)', 'Gider (₺)'],
        rows: [
          ['01.08.2026', 'Satış', 12400, 0],
          ['02.08.2026', 'Operasyon', 0, 1850],
          ['03.08.2026', 'Satış', 9600, 0],
          ['04.08.2026', 'Pazarlama', 0, 2400],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Günlük net ve kümülatif',
        kind: 'calculation',
        headers: ['Tarih', 'Gelir (₺)', 'Gider (₺)', 'Günlük Net (₺)', 'Kümülatif (₺)'],
        rows: [
          ['01.08.2026', '=Girdi!C2', '=Girdi!D2', '=B2-C2', '=D2'],
          ['02.08.2026', '=Girdi!C3', '=Girdi!D3', '=B3-C3', '=E2+D3'],
          ['03.08.2026', '=Girdi!C4', '=Girdi!D4', '=B4-C4', '=E3+D4'],
          ['04.08.2026', '=Girdi!C5', '=Girdi!D5', '=B5-C5', '=E4+D5'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Kategori bazlı ay raporu',
        kind: 'output',
        headers: ['Kategori', 'Gelir (₺)', 'Gider (₺)', 'Net (₺)', 'Marj'],
        rows: [
          ['Satış', '=TOPLA(Girdi!C2:Girdi!C5)', '=TOPLA(Girdi!D2:Girdi!D5)', '=B2-C2', '=D2/B2'],
          ['Operasyon', 0, '=Girdi!D3', '=B3-C3', ''],
          ['Pazarlama', 0, '=Girdi!D5', '=B4-C4', ''],
          ['Genel Toplam', '=TOPLA(B2:B4)', '=TOPLA(C2:C4)', '=B5-C5', '=D5/B5'],
        ],
      },
    ],
    inputs: ['Günlük gelir ve gider tutarları', 'Kategori etiketi (satış, operasyon vb.)', 'Tarih bilgisi'],
    outputs: ['Günlük net kâr ve kümülatif seyir', 'Kategori bazlı marj', 'Dönem genel toplamı'],
    suitableFor: ['Serbest meslek sahipleri', 'Küçük perakende ve hizmet işletmeleri', 'Gelir-gider dengesini günlük izlemek isteyenler'],
    notSuitableFor: ['Cari hesap ve fatura takibi', 'Stok maliyeti'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Kategorileri değiştirebilir miyim?', answer: 'Evet, kategori adlarını kendi işletmenize göre düzenleyebilirsiniz; Çıktı sayfasındaki formüller adlarınızı takip eder.' },
      { question: 'KDV dahil mi ayrı mı girilmeli?', answer: 'Yapı, tutarları KDV dahil kabul eder; tercihinize göre ayrı kolon ekleyebilirsiniz.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
      { question: 'Yıllık karşılaştırma yapabilir miyim?', answer: 'Bu yapı tek dönem içindir; yıllık karşılaştırma için aylık raporu ayrı dosyada saklayabilirsiniz.' },
    ],
    related: ['akıllı-kasa-defteri-ve-nakit-kontrol-sistemi', 'aylık-patron-finans-paneli'],
  },
  {
    name: 'Vergi, SGK ve Maaş Karşılık Ayırma Sistemi',
    category: 'muhasebe-ve-vergi',
    priceTL: 990,
    summary: 'Dönem gelirine göre KDV, kurumlar vergisi, SGK ve maaş karşılıklarını otomatik ayırın; dönem sonunu sürprizsiz karşılayın.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Dönem gelir, gider ve oran girişleri',
        kind: 'input',
        headers: ['Dönem', 'Gelir (₺)', 'Gider (₺)', 'Bordro (₺)', 'KDV Oranı'],
        rows: [
          ['Temmuz 2026', 185000, 96000, 42000, 0.2],
          ['Ağustos 2026', 0, 0, 0, 0.2],
          ['Eylül 2026', 0, 0, 0, 0.2],
          ['Ekim 2026', 0, 0, 0, 0.2],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Karşılık hesapları',
        kind: 'calculation',
        headers: ['Dönem', 'KDV Karşılığı (₺)', 'Kurumlar Karşılığı (₺)', 'SGK+İşveren (₺)', 'Maaş Karşılığı (₺)', 'Toplam (₺)'],
        rows: [
          ['Temmuz 2026', '=Girdi!B2*Girdi!E2', '=Girdi!B2*0.25', '=Girdi!D2*0.3', '=Girdi!D2', '=B2+C2+D2+E2'],
          ['Ağustos 2026', '=Girdi!B3*Girdi!E3', '=Girdi!B3*0.25', '=Girdi!D3*0.3', '=Girdi!D3', '=B3+C3+D3+E3'],
          ['Eylül 2026', '=Girdi!B4*Girdi!E4', '=Girdi!B4*0.25', '=Girdi!D4*0.3', '=Girdi!D4', '=B4+C4+D4+E4'],
          ['Ekim 2026', '=Girdi!B5*Girdi!E5', '=Girdi!B5*0.25', '=Girdi!D5*0.3', '=Girdi!D5', '=B5+C5+D5+E5'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Dönem karşılık raporu',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam ayrılan karşılık (₺)', '=TOPLA(Hesap!F2:F5)'],
          ['KDV karşılığı (₺)', '=TOPLA(Hesap!B2:B5)'],
          ['Kurumlar vergisi (₺)', '=TOPLA(Hesap!C2:C5)'],
          ['SGK + maaş (₺)', '=TOPLA(Hesap!D2:E5)'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Dönem gelir ve gider tutarları', 'Bordro ve oran bilgileri', 'Dönem etiketi (ay adı)'],
    outputs: ['KDV ve kurumlar vergisi karşılığı', 'SGK ve maaş karşılığı', 'Dönem toplam karşılık tutarı'],
    suitableFor: ['Dönem sonu vergi sürprizi yaşamak istemeyenler', 'Bordrosu olan işletmeler', 'Nakit planlamasını karşılıklarla yapanlar'],
    notSuitableFor: ['Beyanname hazırlama', 'Vergi danışmanlığı'],
    requirements: ['Excel 2016 veya üzeri', 'Oranları güncellemek için mali müşavir önerisi'],
    updatePolicy: 'Mevzuat oranları değiştiğinde güncel sürüm satın alma döneminden itibaren 12 ay ücretsiz sunulur; oranlar kullanıcı tarafından da güncellenebilir.',
    faq: [
      { question: 'Oranlar hangi dönem içindir?', answer: 'Demo dosyadaki oranlar örnek değerlerdir. Kendi döneminizin oranlarını mali müşavirinizden teyit ederek Girdi sayfasına işleyin.' },
      { question: 'Kurumlar vergisi oranı nereden değişir?', answer: 'Hesap sayfasındaki 0.25 çarpanını güncel oranla değiştirmeniz yeterlidir.' },
      { question: 'KDV oranı ürün bazında farklıysa?', answer: 'Ürün bazlı oranlarınız varsa Girdi sayfasına satır ekleyip ağırlıklı oranı hesaplayabilirsiniz.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Bu dosya beyanname yerine geçer mi?', answer: 'Hayır. Bu dosya karşılık ayırma ve nakit planlama aracıdır; beyanname mali müşavir tarafından düzenlenir.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
    ],
    related: ['cari-hesap-tahsilat-ve-müşteri-risk-takip-sistemi', 'aylık-patron-finans-paneli'],
  },
  {
    name: 'Stok, Satış ve Nakit Bağlanma Sistemi',
    category: 'stok-ve-uretim',
    priceTL: 1490,
    summary: 'Stok giriş-çıkışını ortalama maliyetle işleyin; stoğa bağlanan nakdi ve devir hızını dönem sonunda görün.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Stok hareket girişleri',
        kind: 'input',
        headers: ['Tarih', 'Ürün', 'Giren', 'Çıkan', 'Birim Fiyat (₺)'],
        rows: [
          ['01.08.2026', 'Ürün A', 200, 0, 45],
          ['03.08.2026', 'Ürün B', 120, 0, 80],
          ['05.08.2026', 'Ürün A', 0, 90, 45],
          ['08.08.2026', 'Ürün B', 0, 60, 80],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Ortalama maliyet ve bağlanan nakit',
        kind: 'calculation',
        headers: ['Ürün', 'Giren Adet', 'Çıkan Adet', 'Kalan Adet', 'Ort. Maliyet (₺)', 'Bağlanan Nakit (₺)'],
        rows: [
          ['Ürün A', '=TOPLA(Girdi!C2:Girdi!C5)', '=TOPLA(Girdi!D2:Girdi!D5)', '=B2-C2', '=Girdi!E2', '=D2*E2'],
          ['Ürün B', '=Girdi!C3', '=Girdi!D5', '=B3-C3', '=Girdi!E3', '=D3*E3'],
          ['Genel Toplam', '=B2+B3', '=C2+C3', '=D2+D3', '', '=F2+F3'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Stok ve devir raporu',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Stoğa bağlanan toplam nakit (₺)', '=Hesap!F4'],
          ['Toplam stok adedi', '=Hesap!D4'],
          ['Dönem çıkış adedi', '=Hesap!C4'],
          ['Devir hızı (dönem)', '=Hesap!C4/Hesap!D4'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Stok giriş ve çıkış adetleri', 'Birim alış fiyatı', 'Ürün adı'],
    outputs: ['Kalan stok adedi ve ortalama maliyet', 'Stoğa bağlanan nakit tutarı', 'Dönem devir hızı'],
    suitableFor: ['Perakende ve toptan satıcılar', 'Üretim yapan küçük KOBİ\'ler', 'Stokta nakit bağlanmasını ölçmek isteyenler'],
    notSuitableFor: ['Depo yönetim sistemi yerine', 'Cari hesap takibi'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Ortalama maliyet nasıl hesaplanıyor?', answer: 'Basit ortalama maliyet yöntemi kullanılır; farklı yöntem için formülü kendi politikalarınıza göre düzenleyebilirsiniz.' },
      { question: 'Birden fazla depo girilebilir mi?', answer: 'Girdi sayfasına Depo kolonu ekleyerek veya depo başına satır grubu oluşturarak izleyebilirsiniz.' },
      { question: 'Devir hızı neyi gösterir?', answer: 'Dönem içinde stoğun kaç kez yenilendiğini gösterir; düşük devir, stoğa fazla nakit bağlandığına işaret eder.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['günlük-gelir-gider-ve-gerçek-kârlılık-sistemi', 'kobi-finans-yönetim-paketi'],
  },
  {
    name: 'POS, Komisyon ve Net Tahsilat Kontrol Sistemi',
    category: 'satis-ve-fiyatlama',
    priceTL: 990,
    summary: 'POS kanallarının brüt satışını, komisyon ve iade düşüldükten sonraki net tahsilatını karşılaştırın; kanal maliyetini görün.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'POS kanal hareketleri',
        kind: 'input',
        headers: ['Tarih', 'Kanal', 'Brüt Satış (₺)', 'İade (₺)', 'Komisyon Oranı'],
        rows: [
          ['03.08.2026', 'POS Banka A', 21400, 800, 0.02],
          ['04.08.2026', 'POS Banka B', 16800, 0, 0.025],
          ['05.08.2026', 'Online', 9200, 300, 0.035],
          ['06.08.2026', 'POS Banka A', 19800, 0, 0.02],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Kanal bazlı net tahsilat',
        kind: 'calculation',
        headers: ['Kanal', 'Brüt (₺)', 'İade (₺)', 'Komisyon (₺)', 'Net Tahsilat (₺)', 'Net Oran'],
        rows: [
          ['POS Banka A', '=TOPLA(Girdi!C2:Girdi!C5)', '=TOPLA(Girdi!D2:Girdi!D5)', '=(B2-C2)*Girdi!E2', '=B2-C2-D2', '=E2/B2'],
          ['POS Banka B', '=Girdi!C3', '=Girdi!D3', '=(B3-C3)*Girdi!E3', '=B3-C3-D3', '=E3/B3'],
          ['Online', '=Girdi!C4', '=Girdi!D4', '=(B4-C4)*Girdi!E4', '=B4-C4-D4', '=E4/B4'],
          ['Genel Toplam', '=TOPLA(B2:B4)', '=TOPLA(C2:C4)', '=TOPLA(D2:D4)', '=TOPLA(E2:E4)', ''],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Kanal maliyet raporu',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam net tahsilat (₺)', '=Hesap!E5'],
          ['Toplam komisyon maliyeti (₺)', '=Hesap!D5'],
          ['En düşük net oranlı kanal', '=INDEX(Hesap!A2:A4;MATCH(MIN(Hesap!F2:F4);Hesap!F2:F4;0))'],
          ['İade oranı', '=Hesap!C5/Hesap!B5'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Kanal adı ve brüt satış', 'İade tutarı ve komisyon oranı', 'İşlem tarihi'],
    outputs: ['Kanal bazlı net tahsilat', 'Komisyon maliyeti', 'İade oranı ve en pahalı kanal'],
    suitableFor: ['Çoklu POS kullanan perakendeciler', 'Online satış yapanlar', 'Kanal maliyetini karşılaştırmak isteyenler'],
    notSuitableFor: ['Kasa defteri', 'Stok takibi'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Komisyon oranlarını nereden güncellerim?', answer: 'Girdi sayfasındaki komisyon oranı kolonundan her işlem için ayrı ayrı girebilirsiniz.' },
      { question: 'İade nasıl etki eder?', answer: 'İade tutarı brüt satıştan düşülür; komisyon net tutar üzerinden hesaplanır.' },
      { question: 'Kanal sayısını artırabilir miyim?', answer: 'Evet, Girdi sayfasına satır ekleyip Hesap sayfasındaki formül aralıklarını genişletmeniz yeterlidir.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['günlük-gelir-gider-ve-gerçek-kârlılık-sistemi', 'akıllı-kasa-defteri-ve-nakit-kontrol-sistemi'],
  },
  {
    name: 'Aylık Patron Finans Paneli',
    category: 'finansal-analiz',
    priceTL: 2490,
    summary: 'Ciro, net kâr, nakit, alacak günü ve FAVÖK göstergelerini aylık tek panelde toplayın; trendi yön tablosuyla okuyun.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Aylık finansal veri girişleri',
        kind: 'input',
        headers: ['Ay', 'Satış (₺)', 'Tahsilat (₺)', 'Gider (₺)', 'Maaş (₺)'],
        rows: [
          ['Mart 2026', 182000, 150000, 96000, 42000],
          ['Nisan 2026', 196000, 171000, 102000, 42000],
          ['Mayıs 2026', 188000, 165000, 98000, 44000],
          ['Haziran 2026', 214000, 180000, 108000, 44000],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Finansal göstergeler',
        kind: 'calculation',
        headers: ['Ay', 'Ciro (₺)', 'Net Kâr (₺)', 'Net Marj', 'Nakit Akışı (₺)', 'Alacak Günü'],
        rows: [
          ['Mart 2026', '=Girdi!B2', '=B2-Girdi!D2-Girdi!E2', '=C2/B2', '=Girdi!C2-Girdi!D2-Girdi!E2', '=Girdi!B2/30'],
          ['Nisan 2026', '=Girdi!B3', '=B3-Girdi!D3-Girdi!E3', '=C3/B3', '=Girdi!C3-Girdi!D3-Girdi!E3', '=Girdi!B3/30'],
          ['Mayıs 2026', '=Girdi!B4', '=B4-Girdi!D4-Girdi!E4', '=C4/B4', '=Girdi!C4-Girdi!D4-Girdi!E4', '=Girdi!B4/30'],
          ['Haziran 2026', '=Girdi!B5', '=B5-Girdi!D5-Girdi!E5', '=C5/B5', '=Girdi!C5-Girdi!D5-Girdi!E5', '=Girdi!B5/30'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Yönetim özeti ve trend',
        kind: 'output',
        headers: ['Gösterge', 'Son Değer', 'Önceki', 'Değişim'],
        rows: [
          ['Ciro (₺)', '=Hesap!B5', '=Hesap!B4', '=B2-C2'],
          ['Net Kâr (₺)', '=Hesap!C5', '=Hesap!C4', '=B3-C3'],
          ['Net Marj', '=Hesap!D5', '=Hesap!D4', '=B4-C4'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Aylık satış, tahsilat ve gider tutarları', 'Maaş ödemeleri', 'Dönem etiketi (ay adı)'],
    outputs: ['Ciro, net kâr ve marj göstergeleri', 'Nakit akışı ve alacak günü', 'Önceki döneme göre değişim'],
    suitableFor: ['İşletme sahipleri ve yöneticiler', 'Aylık özet rapor arayanlar', 'Yatırımcı sunumu hazırlayanlar'],
    notSuitableFor: ['Günlük operasyon takibi', 'Detaylı muhasebe'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'FAVÖK nerede hesaplanıyor?', answer: 'Demo modelde net kâr üzerinden özet verilir; FAVÖK için faiz ve amortisman kalemlerini Girdi sayfasına ekleyip formülü genişletebilirsiniz.' },
      { question: 'Alacak günü nasıl yorumlanır?', answer: 'Basit modelde satışın 30\'a bölümüyle gösterilir; gerçek alacak günü için cari hesap sistemindeki vade verisiyle değiştirmeniz önerilir.' },
      { question: 'Panelde hangi göstergeler var?', answer: 'Ciro, net kâr, net marj, nakit akışı ve alacak günü; dilerseniz kendi göstergelerinizi ekleyebilirsiniz.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['kobi-finans-yönetim-paketi', 'günlük-gelir-gider-ve-gerçek-kârlılık-sistemi'],
  },
  {
    name: 'Proje ve İş Bazında Gerçek Kârlılık Sistemi',
    category: 'satis-ve-fiyatlama',
    priceTL: 2490,
    summary: 'Her işin gelirini direkt giderlerle eşleştirin; iş bazında gerçek kâr ve marjı çıkarın, kaynakları kârlı işlere yönlendirin.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'İş ve gelir-gider girişleri',
        kind: 'input',
        headers: ['İş No', 'İş Adı', 'Gelir (₺)', 'Direkt Gider (₺)', 'Süre (gün)'],
        rows: [
          ['PRJ-101', 'Pano Montajı', 48000, 31500, 12],
          ['PRJ-102', 'Bakım Anlaşması', 26000, 14800, 5],
          ['PRJ-103', 'Özel Üretim', 37000, 29000, 18],
          ['PRJ-104', 'Danışmanlık', 22000, 6400, 4],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'İş bazlı kârlılık',
        kind: 'calculation',
        headers: ['İş No', 'İş Adı', 'Gelir (₺)', 'Maliyet (₺)', 'Kâr (₺)', 'Marj', 'Günlük Kâr (₺)'],
        rows: [
          ['PRJ-101', '=Girdi!B2', '=Girdi!C2', '=Girdi!D2', '=C2-D2', '=E2/C2', '=E2/Girdi!E2'],
          ['PRJ-102', '=Girdi!B3', '=Girdi!C3', '=Girdi!D3', '=C3-D3', '=E3/C3', '=E3/Girdi!E3'],
          ['PRJ-103', '=Girdi!B4', '=Girdi!C4', '=Girdi!D4', '=C4-D4', '=E4/C4', '=E4/Girdi!E4'],
          ['PRJ-104', '=Girdi!B5', '=Girdi!C5', '=Girdi!D5', '=C5-D5', '=E5/C5', '=E5/Girdi!E5'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'İş öncelik raporu',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam kâr (₺)', '=TOPLA(Hesap!E2:E5)'],
          ['Ağırlıklı marj', '=TOPLA(Hesap!E2:E5)/TOPLA(Hesap!C2:C5)'],
          ['En kârlı iş', '=INDEX(Hesap!B2:B5;MATCH(MAX(Hesap!F2:F5);Hesap!F2:F5;0))'],
          ['Zarar eden iş sayısı', '=EĞERSAY(Hesap!E2:E5;"<0")'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['İş adı ve toplam geliri', 'Direkt maliyet ve süre', 'İş numarası'],
    outputs: ['İş bazında kâr ve marj', 'Günlük kâr karşılaştırması', 'Zarar eden iş uyarısı'],
    suitableFor: ['Proje bazlı çalışan üreticiler', 'Hizmet işletmeleri', 'Kaynak tahsisini kâra göre yapmak isteyenler'],
    notSuitableFor: ['Genel gider dağıtımı yapılmadan şirket kârlılığı', 'Stok takibi'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Mevzuattan bağımsız yapıdır; iyileştirme sürümleri satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Genel giderler nereye yazılır?', answer: 'Bu yapı iş bazlı direkt giderleri esas alır. Genel gider dağıtımı için ayrı bir genel gider satırı ekleyebilirsiniz.' },
      { question: 'Günlük kâr neden önemli?', answer: 'Süresi uzun işler toplamda kârlı görünse de günlük kâr düşük olabilir; kaynak tahsisi günlük kâra göre önceliklendirilmelidir.' },
      { question: 'İş eklerken formül uzar mı?', answer: 'Hayır, yeni iş satırına veriyi girip Hesap sayfasındaki formülleri satır aralığına kopyalamanız yeterlidir.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['günlük-gelir-gider-ve-gerçek-kârlılık-sistemi', 'aylık-patron-finans-paneli'],
  },
  {
    name: 'KOBİ Finans Yönetim Paketi',
    category: 'butce-ve-planlama',
    priceTL: 7900,
    summary: 'Kasa, cari, banka ve stok sistemlerini tek yapıda birleştiren paket. Aylık yönetim özeti ve karşılık planıyla dönem sonunu net görün.',
    fileFormat: 'xlsx',
    hasMacros: false,
    minExcelVersion: 'Excel 2016 ve üzeri',
    macCompatible: true,
    sheetsCompatibility: 'full',
    version: '1.0.0',
    updatedAt: '2026-08-06',
    sheets: [
      {
        name: 'Girdi',
        purpose: 'Konsolide aylık veri girişi',
        kind: 'input',
        headers: ['Ay', 'Kasa (₺)', 'Cari Tahsilat (₺)', 'Banka (₺)', 'Stok Alışı (₺)', 'Operasyon Gideri (₺)'],
        rows: [
          ['Mart 2026', 86000, 74000, 120000, 46000, 78000],
          ['Nisan 2026', 91000, 79000, 126000, 48000, 82000],
          ['Mayıs 2026', 88000, 76000, 122000, 45000, 79000],
          ['Haziran 2026', 98000, 86000, 134000, 52000, 85000],
        ],
      },
      {
        name: 'Hesap',
        purpose: 'Konsolide nakit modeli',
        kind: 'calculation',
        headers: ['Ay', 'Toplam Nakit (₺)', 'Nakit Değişimi (₺)', 'Kâr Tahmini (₺)', 'Risk Skoru'],
        rows: [
          ['Mart 2026', '=Girdi!B2+Girdi!C2+Girdi!D2', 0, '=Girdi!C2+Girdi!D2-Girdi!E2-Girdi!F2', '=EĞER(B2<200000;"Düşük";"Orta")'],
          ['Nisan 2026', '=Girdi!B3+Girdi!C3+Girdi!D3', '=B3-B2', '=Girdi!C3+Girdi!D3-Girdi!E3-Girdi!F3', '=EĞER(B3<200000;"Düşük";"Orta")'],
          ['Mayıs 2026', '=Girdi!B4+Girdi!C4+Girdi!D4', '=B4-B3', '=Girdi!C4+Girdi!D4-Girdi!E4-Girdi!F4', '=EĞER(B4<200000;"Düşük";"Orta")'],
          ['Haziran 2026', '=Girdi!B5+Girdi!C5+Girdi!D5', '=B5-B4', '=Girdi!C5+Girdi!D5-Girdi!E5-Girdi!F5', '=EĞER(B5<200000;"Düşük";"Orta")'],
        ],
      },
      {
        name: 'Çıktı',
        purpose: 'Aylık yönetim özeti',
        kind: 'output',
        headers: ['Gösterge', 'Değer'],
        rows: [
          ['Toplam nakit (₺)', '=Hesap!B5'],
          ['Nakit değişimi (₺)', '=Hesap!C5'],
          ['Kâr tahmini (₺)', '=Hesap!D5'],
          ['Risk skoru', '=Hesap!E5'],
          ['DEMO — Excel Arşiv · excelarsiv.com', ''],
        ],
      },
    ],
    inputs: ['Kasa, banka ve cari tahsilat toplamları', 'Stok alışı ve operasyon giderleri', 'Aylık dönem etiketi'],
    outputs: ['Konsolide nakit ve kâr tahmini', 'Aylık nakit değişimi', 'Risk skoru ve yönetim özeti'],
    suitableFor: ['Finans süreçlerini tek pakette toplamak isteyen KOBİ\'ler', 'Aylık yönetim toplantısı için özet arayanlar', 'Bireysel sistemleri paket fiyatına almak isteyenler'],
    notSuitableFor: ['Tek bir işi çözmek isteyenler (bireysel sistemler daha uygundur)', 'Çok kullanıcılı muhasebe sistemi'],
    requirements: ['Excel 2016 veya üzeri'],
    updatePolicy: 'Paket, içerdiği sistemlerin güncellemelerini kapsar; mevzuat değişikliği olursa güncel sürüm satın alma döneminden itibaren 12 ay ücretsiz sunulur.',
    faq: [
      { question: 'Pakette hangi sistemler var?', answer: 'Kasa defteri, nakit akışı, cari hesap, banka/kredi, çek–senet, gelir-gider, vergi/SGK karşılık, stok ve POS kontrolü ile patron paneli özetine dayalı konsolide yönetim modeli.' },
      { question: 'Bireysel sistemlerden farkı ne?', answer: 'Bireysel sistemler tek işi çözer; paket bu verileri konsolide ederek aylık yönetim özeti üretir.' },
      { question: 'İçerik daha sonra genişler mi?', answer: 'Paket sürümü, kapsadığı sistemlerin güncellemeleriyle birlikte yenilenir.' },
      { question: 'Excel sürümüm eski, çalışır mı?', answer: 'Excel 2016 ve üzeri gerekir; kullanılan işlevler standarttır.' },
      { question: 'Kilitli mi? Değiştirebilir miyim?', answer: 'Girdi alanları serbesttir; formül sayfaları şifresiz korumadadır, kaldırıp inceleyebilirsiniz.' },
      { question: 'Lisans tek kullanıcılık mı?', answer: 'Evet, tek lisans tek kullanıcıdır; aynı kullanıcının makul sayıdaki cihazında kullanılabilir.' },
    ],
    related: ['akıllı-kasa-defteri-ve-nakit-kontrol-sistemi', '13-haftalık-nakit-akışı-ve-ödeme-planlama-sistemi', 'aylık-patron-finans-paneli'],
  },
];
